language: python
matrix:
  include:
  - python: 2.7
    env:
    - secure: "uaTZs64F+bWb7gbAyBKzQauBcaW3B7zzcCnDCle+5dGOkwC6SofFTVVT/EY3LcbnuIODzJdYLz3qZy480+T6jlNUA3Kqp25DYx8ypHdlGt8/7ocDoxuPJRIcUFZfTg9Y5kDaWU2hpvECzNF6urW2jehLm3uCP2pM710ffQV+QZhNmp6Ffy/qMj8zMODboWcVsQpLz3szDr3hwJA/1ig5cT/GuTurrAmuvP/O5aMoEnVncQ10sITFCl1nUDk1jzvA1P24qMGZlgj4NVEZ5rMuN7zzSR4T0fu+D42wj4fxkh8kuPZy43wFVER3w5n0xV2ZEqHf95JaEvq+BQRZmjodnlhQN2lRE93DlXenfNct5tNs/JnBCenURPULYslooTPENiRwBETZGVhY+NXUJ/XTW5gEELNu3tzR1pq8r9k487dZqJXWb9GAUl/pJsUeMDAgpbMEUjFFA7B+9QsiJvaleOSV8mx7L2ycngxSmPIIGJR/jWEA2YXjn8WEx98a1ZIiqr0jKIOSI3YvN4gJ//yBt1IoxZBVz6BZ7h1no7tTEk0qS/oy52HSh2PWTy2pHMfUrLBb86UZ3SszxMeoLJTHDsimNqknudeb7cB535+Kaauc+34oj8g9qaWqEzvmh9OR0EHka7BGUMmSF5SJfiPA2HdumhrKkhFfe3W4kWvestE="
    - secure: "nTSWshX+02z9JLkT7ppZ/O0MGfVu5ZkG/9FTDlr+Fpx3NyA8bZynxaDkbRqJxJiCqFidjZzP6dUhcLJtwVuqLPAXaUeAP3Lp1MCmR19CFnADOW247u3nSwyzivxBAXLpV4CBeyQWruMGCLoNRKsQ97azCPqF9y/l5BAza/jr5Agj7BkrUPLJauSo4h/tI6Em8zDx3a93nfwJOxdnx+1zJOV78AvglRMwAMnjpt8JRK0ptRkf+QBAkN7iAWKYNvVVIRhuda+cCUAfH8pQlYOkh0tLR/U98CU3IuSLFhdRjygjabXRs8jaEi6JLJTp4KGbOhabyOEn27OiA77vU25tad4Y8Mk3gL2l12/ZORujci30FrnIGd+wJ9dApDhgQbpJDuAaS79CVUg0MFN8yO7mHW3znzQ3VHoZHbNZUvSufQ0KX4meEoqEkVB6+IJnxrMzxg9ouYhv1riNXXCXFxvCZb3k8jwZrWZb13xeVvbow5g/qKwqjKgTXg7vrepp9NHmj7T2zDeBbKX38NdDrKC6V0V2+z03CUwZbU+duALacdB24QbjL1r9HrdkRSrig07+wmAj0vIldUsQv/5E8LChsUt0JAXPGcSjaiun2xduskBBDDHKJDbbKJsK3M6OZRsqhkKNuwBe3BJ35Bgcx3LfwP5Sut4vOpkSfYkH329oV6Y="
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.db.livdet2013 import get_config; print(get_config())'
- ./bin/coverage run --source=bob.db.livdet2013 ./bin/nosetests -sv
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-wheel.sh
- chmod a+x upload-wheel.sh
- ./upload-wheel.sh
